/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jackie;

import java.awt.event.ActionListener;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author waltersiu
 */
public class LoginPageView extends Page implements Observer {
    private Page parent;
    private DatabaseOperation dbm;
    /**
     * Creates new form LoginPageView
     */
    public LoginPageView(Page parent, DatabaseOperation dbm){
        super(parent);
        this.parent = parent;
        this.dbm = dbm;
        this.setVisible(true);
        initComponents();
        parent.setVisible(false);
    }
    
    public void submitAddOnClickListener(ActionListener al){
        submitButton.addActionListener(al);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPagePanel = new javax.swing.JPanel();
        labelLogin = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        inputPassword = new javax.swing.JTextField();
        inputEmail = new javax.swing.JTextField();
        labelPassword = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Movie Booking System");

        loginPagePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelLogin.setFont(new java.awt.Font("新細明體", 1, 18)); // NOI18N
        labelLogin.setText("Login");
        labelLogin.setToolTipText("");
        loginPagePanel.add(labelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 59, 30));

        submitButton.setText("Login");
        loginPagePanel.add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 90, 30));
        loginPagePanel.add(inputPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 145, 190, -1));
        loginPagePanel.add(inputEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 95, 190, -1));

        labelPassword.setText("Password");
        loginPagePanel.add(labelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        labelEmail.setText("Email");
        loginPagePanel.add(labelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 50, -1));

        backButton.setText("Back");
        loginPagePanel.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPageView(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputPassword;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JPanel loginPagePanel;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables

    public String getInputEmail(){
        return this.inputEmail.getText();
    }
    
    public String getInputPassword(){
        return this.inputPassword.getText();
    }
    
    public JButton getBackButton(){
        return this.backButton;
    }
    
    //Receive compare date result from model and pop-up related message to user
    @Override
    public void update(Observable model, Object arg) {
        this.setVisible(true);
        LoginPageModel loginModel = (LoginPageModel)model;
        if(loginModel.getResult().equals("nodata")){
            JOptionPane.showMessageDialog(this, "Please register first!");
        }
        if(loginModel.getResult().equals("success")){
            JOptionPane.showMessageDialog(this, "Login Success!");
            this.setVisible(false);
            LoginPageView.this.parent.setVisible(true);
            HomePageView homePageView = new HomePageView(parent);
            HomePageModel homePageModel = new HomePageModel(this.dbm);
            HomePageController homePageController = new HomePageController(homePageModel, homePageView);
        } else if(loginModel.getResult().equals("wrongEmail")){
            JOptionPane.showMessageDialog(this, "No record with your Email address!");
        } else if(loginModel.getResult().equals("wrongPassword")){
            JOptionPane.showMessageDialog(this, "Your password is not match with record!");
        } else if(loginModel.getResult().equals("emailempty")){
            JOptionPane.showMessageDialog(this, "Please enter your email!");
        } else if(loginModel.getResult().equals("passwordempty")){
            JOptionPane.showMessageDialog(this, "Please enter your password!");
        }
    }
}
