/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jackie;

import java.util.Observable;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author jacki
 */
public class MovieDetailPageView extends Page{

    /**
     * Creates new form MovieDetailPageView
     */
    public MovieDetailPageView(Page parent) {
        super(parent);
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        movieName = new javax.swing.JLabel();
        movieLength = new javax.swing.JLabel();
        casting = new javax.swing.JLabel();
        showTime = new javax.swing.JButton();
        back = new javax.swing.JButton();
        description = new javax.swing.JLabel();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Movie Booking System");
        setResizable(false);

        movieName.setText("jLabel1");
        movieName.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        movieLength.setText("jLabel2");
        movieLength.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        casting.setText("jLabel3");
        casting.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        showTime.setText("Enter ShowTime Page");
        showTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTimeActionPerformed(evt);
            }
        });

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        description.setText("jLabel1");
        description.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        image.setText("jLabel1");
        image.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(showTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(description, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                    .addComponent(movieLength, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(casting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(movieName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(back))
            .addGroup(layout.createSequentialGroup()
                .addComponent(movieName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(movieLength, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(casting, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        image.getAccessibleContext().setAccessibleName("image");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showTimeActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed

    }//GEN-LAST:event_backActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel casting;
    private javax.swing.JLabel description;
    private javax.swing.JLabel image;
    private javax.swing.JLabel movieLength;
    private javax.swing.JLabel movieName;
    private javax.swing.JButton showTime;
    // End of variables declaration//GEN-END:variables

    
    @Override
    public void update(Observable o, Object arg) {
        showMovieDetail(((MovieDetailPageModel)o));
    }
    
    public void showMovieDetail(MovieDetailPageModel model){
        this.casting.setText("<html>Casting:<br>"+model.movie.getCastings()+"</html>");
        this.movieLength.setText("<html>Length:<br>"+String.valueOf(model.movie.getLength())+"</html>");
        this.description.setText( "<html><p style=\"width:350px\">Description:<br>"+model.movie.getDescription()+"</p></html>");
        this.movieName.setText("<html>Movie name:<br>" + model.movie.getName()+ "</html>");
        String imagePath = model.movie.getImage();
        this.image.setIcon(new javax.swing.ImageIcon(getClass().getResource(imagePath))); // NOI18N
    }
   
    
    public void addController(MovieDetailPageController controller){
        showTime.addActionListener(controller);
    }

    public JButton getBack() {
        return back;
    }

    public void setBack(JButton back) {
        this.back = back;
    }

    public JLabel getCasting() {
        return casting;
    }

    public void setCasting(JLabel casting) {
        this.casting = casting;
    }

    public JLabel getDescription() {
        return description;
    }

    public void setDescription(JLabel description) {
        this.description = description;
    }

    public JLabel getjLabel1() {
        return image;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.image = jLabel1;
    }

    public JLabel getMovieLength() {
        return movieLength;
    }

    public void setMovieLength(JLabel movieLength) {
        this.movieLength = movieLength;
    }

    public JLabel getMovieName() {
        return movieName;
    }

    public void setMovieName(JLabel movieName) {
        this.movieName = movieName;
    }

    public JButton getShowTime() {
        return showTime;
    }

    public void setShowTime(JButton showTime) {
        this.showTime = showTime;
    }
    
}
