package com.jackie;


import java.awt.event.ActionListener;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author waltersiu
 */
public class RegisterPageView extends Page implements Observer{

    /**
     * Creates new form RegisterPage
     */
    public RegisterPageView(Page parent) {
        super(parent);
        this.setVisible(true);
        initComponents();
        parent.setVisible(false);
    }
    
    public void submitAddOnClickListener(ActionListener al){
        submitButton.addActionListener(al);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelName = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        inputName = new javax.swing.JTextField();
        inputConfirm = new javax.swing.JTextField();
        inputEmail = new javax.swing.JTextField();
        labelReg = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        inputPassword = new javax.swing.JTextField();
        labelConfirm = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Movie Booking System");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelName.setText("Name");
        jPanel1.add(labelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        labelPassword.setText("Password");
        jPanel1.add(labelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        labelEmail.setText("Email");
        jPanel1.add(labelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));
        jPanel1.add(inputName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 195, 116, -1));
        jPanel1.add(inputConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 155, 116, -1));
        jPanel1.add(inputEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 75, 116, -1));

        labelReg.setFont(new java.awt.Font("新細明體", 1, 14)); // NOI18N
        labelReg.setText("Registration");
        jPanel1.add(labelReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        submitButton.setText("Register");
        jPanel1.add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 90, 30));
        jPanel1.add(inputPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 115, 116, -1));

        labelConfirm.setText("Confirm Password");
        jPanel1.add(labelConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.back();
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField inputConfirm;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputName;
    private javax.swing.JTextField inputPassword;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelConfirm;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelReg;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables

    
    public String getInputEmail(){
        return inputEmail.getText();
    }
    
    public String getInputPassword(){
        return inputPassword.getText();
    }
    
    public String getInputConfirm(){
        return inputConfirm.getText();
    }
    
    public String getInputName(){
        return inputName.getText();
    }
    
    //Receive Compare data result from Model and pop-up related error/success message to user
    @Override
    public void update(Observable model, Object arg) {
        RegisterPageModel registerModel = (RegisterPageModel)model;
        if(registerModel.getResult().equals("equal")){
            JOptionPane.showMessageDialog(this, "Email have been registered...");
        } else if(registerModel.getResult().equals("")){
            JOptionPane.showMessageDialog(this, "Register success!");
            this.setVisible(false);
            this.getParent().setVisible(true);
        } else if(registerModel.getResult().equals("notmatch")){
            JOptionPane.showMessageDialog(this, "Please enter a valid email!");
        } else if(registerModel.getResult().equals("passwordempty")){
            JOptionPane.showMessageDialog(this, "Please enter password!");
        } else if(registerModel.getResult().equals("passwordnotmatch")){
            JOptionPane.showMessageDialog(this, "Please confirm your password again!");
        } else if(registerModel.getResult().equals("nameempty")){
            JOptionPane.showMessageDialog(this, "Please enter your name!");
        } else if(registerModel.getResult().equals("emailempty")){
            JOptionPane.showMessageDialog(this, "Please enter your email!");
        } else if(registerModel.getResult().equals("confirmempty")){
            JOptionPane.showMessageDialog(this, "Please enter confirm password!!");
        }
    }
}
